veelenga/awesome-crystal

README.md
=> Add Template Engine section

README.md
Guardian is a file change wathcer. It depends on a `.guardian.yml` file.
Example:
```yaml
files: **/*.cr
run: crystal build ./src/hey.cr
---
files: ./shards.yml
run: crystal deps
```
When you run `guardian` it will start to watch `files` keys and when change occured, it will run `run` keys in sequence.
=> Add guardian to misc.

README.md
Add entry for JWT implementation: https://github.com/greyblake/crystal-jwt
=> Add jwt entry

README.md
Maybe it's time to create section `Algorithms and data structures`)
=> add Bloom Filter

README.md
Wasn't sure where to put Kilt, any better idea?
=> Added slang and kilt

README.md
Add link to Heroku-like memorable random names to use in your apps or anywhere else.
=> Add haikunator to Misc

README.md
=> Add Crank to Services and Apps

README.md
This adds [Helmet](https://github.com/EvanHahn/crystal-helmet) to this list.
=> Add Helmet to list

README.md
Hopefully this is self-explanatory.  Let me know if you have any questions.  Thanks!
=> Add primes library info.

README.md
Include a link to Radix project, which provides a generic implementation of the Radix Tree data structure.
Please consider this for inclusion.
:heart: :heart: :heart:
=> Add Radix Tree implementation

README.md
Hi. I've changed my GitHub username. Thank you.
=> Change crenv repository url

README.md
=> Add openweather.cr

README.md
Recently changed my Github username.
=> Updated link to Commander.

README.md
This `random.cr` library no longer exists.
=> Remove random.cr

README.md
Add entries for [Glosbe](https://github.com/greyblake/crystal-glosbe) and [Google Translate](https://github.com/greyblake/crystal-google_translate)
=> add Glosbe and GoogleTranslate entries

README.md
add entry for [observable](https://github.com/TPei/observable) a crystal Observer implementation
=> add observable

README.md
`inflector.cr`, a port of `ActiveSupport::Inflector`
Not sure if there is a better location than misc?
=> add inflector under misc

README.md
Latter repo is the one with the actual code.
=> Swap serial.cr to serialport.cr

README.md
=> Add link to Open Exchange Rates API wrapper

README.md
Wasn't sure what to do for an *update* so tossed it in here :)
=> add crystal-lang/crystal-mysql, update crystal-sqlite3

README.md
added "denetmen - useful check library for Crystal"
=> added new library [denetmen]

README.md
Ran specs. Everything is good 👍
=> Adds sentry project

README.md
Let me know if this is keeping within the guidelines.
Best,
Andrei
=> Add dotacr to Third-party APIs

README.md
Hi! I added my [serve](https://github.com/SuperPaintman/serve) static HTTP server.
=> Add `serve` web server

README.md
Hi, it's me again. I added my [ctags](https://github.com/SuperPaintman/crystal-ctags) generator for **Crystal**
=> Add `crystal-ctags`

README.md
Hello! I added [etag](https://github.com/SuperPaintman/etag) library to generate HTTP ETags
=> Added etag library

README.md
Hi! I added [response_time](https://github.com/SuperPaintman/response-time) http handler.
This module set response HTTP Header like this:
> X-Response-Time: 0.0722ms
=> Added response_time http handler

README.md
I added the interpreter for the charly programming language I made during the last couple months.
=> Add charly programming language

README.md
Add my new project: [Crystagiri](https://github.com/madeindjs/Crystagiri) - An Html Reader / parser like [Nokogiri](https://github.com/sparklemotion/nokogiri) Ruby gem
=> Add my Crystagiri project

README.md
Ensure that your change covers the following:
Excessive information like
**"... written in Crystal"** etc. is ommited if possible
=> Add quartz

README.md
Ensure that your change covers the following:
Excessive information like
**"... written in Crystal"** etc. is ommited if possible
=> Add dispatch

README.md
[sendgrid.cr](https://github.com/dlanileonardo/sendgrid.cr)
Added to **Email** section
There is no excessive information like
=> Sendgrid.cr

README.md
[ENTRY_NAME](LINK_TO_RESOURCE)
Added to **SECTION_NAME** section
=> Add soundfile

README.md
[ENTRY_NAME](LINK_TO_RESOURCE)
Added to **SECTION_NAME** section
=> add kgen, kemalyst-i18n, kemalyst-model

README.md
[asdf-crystal](https://github.com/marciogm/asdf-crystal)
Added to **Environment Management** section
=> Add asdf-crystal

README.md
[request_id](https://github.com/SuperPaintman/request-id)
Added to **Framework Components** section
=> request_id

README.md
Added turkish-number library. 
Turn integers into the Turkish words.
=> Add turkish-number

README.md
[any_hash.cr](https://github.com/Sija/any_hash.cr)
Added to **Misc** section
=> Add any_hash.cr

README.md
[raven.cr](https://github.com/sija/raven.cr)
=> Add raven.cr

README.md
[http-protection](https://github.com/rogeriozambon/http-protection)
Added to **HTTP** section
=> Added http-protection

README.md
[jennifer](https://github.com/imdrasil/jennifer.cr) 
Added to **ORM/ODM Extensions** section
[hermes](https://github.com/imdrasil/hermes.cr) 
Added to **Search** section
[sam](https://github.com/imdrasil/sam.cr) 
Added to **Task management** section
=> Added jennifer, sam, hermes

README.md
I am creator of Cake :3 
https://github.com/axvm/cake
Cake (Crystal Make) is a make\cmake\...\rake-like utility tool for tasks management and build automation. Task must be defined in real Crystal language. 
Shard contains 2 components - CLI application and runtime library for tasks. 
Works absolutely transparent without pain.
=> Added Cake to Task management category

README.md
=> Add x11-cr to C bindings

README.md
Standardized multi-provider OAuth2 authentication
=> Add multi_auth

README.md
For the list to continue to be awesome we need to cleanup projects that aren't supported.  The web frameworks I've have crossed off here haven't been updated in at least a year and we probably don't want people wasting time going there.
=> Strikethrough of dead web frameworks

README.md
Updated kemalyst model to granite-orm and added CRelease which is a shard that helps version and git tag your shards.
=> Updated kemalyst model to granite-orm and added Crelease.

README.md
A simple and customizable CLI ProgressBar implementation
=> add progress_bar.cr

README.md
This is my shard to connect to an ArangoDB database
=> [database] ArangoDB HTTP driver

README.md
chuck-norris-holy-quotes
crystal-mysql-crud-example
jihantoro-cr-mysql
jihantoro.sd
kemal-mysql-blog
=> add some examples and funny stuff

README.md
Update README with Pinboard API client.
=> Add Pinboard API client

README.md
- Updated README.md
- Ran specs
=> Add microtest

README.md
Already used in production by https://github.com/vladfaust/soundmemes.cr
=> Add tele.cr

README.md
Added [phoenix.cr](https://github.com/dtcristo/phoenix.cr) - Phoenix Channels client.
=> Add phoenix.cr

README.md
A minimal, CentOS base, image for dockerized Crystal development.
=> Added `crystal-base` docker image

README.md
Now Amber organization is https://github.com/amberframework
=> Update Amber Framework links.

README.md
=> Updated link to moved project

README.md
Many thank for your PR and your answer.
I put my tool in Misc section.
You can move if you want ;-)
=> Add HelpTransl8, a tool for document translators

README.md
=> Add halite and markd

README.md
I added hash_ring. It's an implementation of consistent hash that allow the fast dynamic assignment in distributed server environment.
=> add hash_ring

README.md
- I hope so :)
- Object Oriented actually ;)
- You bet.
- As stable as a library written in an Alpha-stage language gets!
- I'd like to take this moment to thank the `crystal docs` command
- 100% tested code
=> Added markov shard to Algorithms and Data Structures

README.md
@pine http://crystal.pine.moe/en gives 503. Should we remove it from the list now?
Validated with [awesome_bot](https://github.com/dkhamsing/awesome_bot):
<details>
```
> Checking links in README.md
Links to check: 423, 421 unique
001. https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg 
002. https://github.com/sindresorhus/awesome 
003. https://api.travis-ci.org/veelenga/awesome-crystal.svg 
004. https://travis-ci.org/veelenga/awesome-crystal 
005. https://github.com/bayandin/awesome-awesomeness 
006. https://crystalshards.xyz 
007. https://crystal-ann.com 
008. https://github.com/veelenga/awesome-crystal/blob/master/.github/CONTRIBUTING.md 
009. https://github.com/chenkovsky/aho_corasick 
010. https://github.com/MakeNowJust/crystal-diff …
```
=> Fix redirects & remove broken links

README.md
Add a reference to noteesh. Yet another cli for todo list o notes
=> Add noteesh

README.md
A library for sending events to Mixpanel analytics.
=> Add mixpanel-crystal

README.md
Considerably easier than starting from scratch
Yep
Yep
Until proven otherwise
Heavily
100% tested, as always
=> Add GDAX to Third-party APIs

.github/CONTRIBUTING.md
https://github.com/veelenga/awesome-crystal/blob/f6738621a1cdc035a9ec9b11ce2e32fd7f418b78/.github/CONTRIBUTING.md
I'm open for changes and additions. But I think such guidelines have to be as short as possible, so please suggest only the must have points.
=> New Contribution Guidelines

README.md
Hi there!
Thanks so much for including Lucky. I've updating the repo link and description and added a couple Lucky packages that are useful on their own: LuckyRecord and Habitat.
I ran `crystal specs` and they passed.
Thanks for taking a look
=> Update Lucky and add some other Lucky libs

README.md
This PR adds devdocs.io
http://devdocs.io/crystal/ is a useful API & Documentation Browser.
=> Add devdocs.io

README.md
Hello !
I'm adding here the shard I'm working on, because it starts to be stable enough to play with, and I need review for going further into it.
It's an ORM for PostgreSQL, and it already offers lots of features some of the ORM here are not  covering (e.g. cursored each, foreign key constraints, save-point, n+1 and n...(n+1) queries caching)
Note than there's no release yet, as I'm still working hard to cover everything with specs.
=> adding clear to the list

README.md
- I have create a `GUI library` section and add qt5 QML bindings.
- I move libui.cr in this section
=> Add GUI library section

README.md
Link: https://github.com/foliea/firegrid
I created and maintain this project which aims to make pointer-driven interfaces easier and faster for users to operate. It allows you to move the pointer and click quickly to most points on the screen with only a few key strokes.
I would love other people to play with and hopefuly get some feedback.
Thanks for your time!
=> add firegrid

README.md
It is demonstration app using Vue.js with Kemal, inspired by react-kemal-app
=> Add kemal and vue.js chat

README.md
Add elorest/cry - Ability to execute crystal code in a fashion similar to pry edit.
=> Add elorest/cry

README.md
add m3u8 - Generate and parse m3u8 playlists for HTTP Live Streaming
=> add m3u8 generator and parser

README.md
Link: https://github.com/spider-gazelle/spider-gazelle
Hi all, looking to see if you are interested in adding this project to your list.
It's a web framework with a focus on simplicity and speed.
Extending [router.cr](https://github.com/tbrand/router.cr), it uses lazy loading and meta programming to inline (unwrap, pre-process) as much as possible. So once running there is very little overhead, making it faster than kemal or raze.
As well as raw speed, it aims to be the simplest to reason with by matching the Ruby on Rails controller API as much as possible (before, after and around filters etc with the same syntax as Rails) whilst maintaining full inheritance support <- harder than it sounds
We're also more of a NoSQL company so the spider-gazelle model code is built to be the basis for …
=> Add spider-gazelle

README.md
See #258
This PR is a basis for discussion.
=> [WIP] Add libraries included in Crystal stdlib

README.md
Link to the repo: https://github.com/veelenga/ameba
=> Add ameba linter

README.md
=> [halite] update description

README.md
I made this shard for speeding up the development of Web API.
Added to **Data Formats** section:
* [crinder](https://github.com/c910335/crinder) - Class based json renderer
I hope this will also help other Web API developers.
Thanks.
=> Add crinder

README.md
I wrote a Tron-style snake for a [Battlesnake](https://www.battlesnake.io/) competition.  It implements a [voronoi](https://en.wikipedia.org/wiki/Voronoi_diagram) heuristic, connected-component analysis, a basic flood fill, etc.. Worth checking out for the gifs!
=> Added battlesnake_crystal

README.md
Hi there!
Just finished extracting Carbon and would like to put it in the Email list for other to find.
Thanks!
Paul
=> Add Carbon to Email list

README.md
Hello !
I guess it was waited by a lot of _Crystalist_, I've made a proof of concept for covering Crystal code ! 🍾 🍾 🍾 🍾 
Basically, it's working however still with some petty issues.
As of now, there's no releases nor proper testing. I need to gather some insight from end-users, to finalize a first release.
I've tested it on my own librairies [clear](https://github.com/anykeyh/clear) and [tree_template](https://github.com/anykeyh/tree_template) and it works !!
In the near future, I'm planning to integrate with travis and coveralls. Finally covering badge for crystal will become reality 👍
Please share me your thought !
=> Crystal Coverage

README.md
Hi @veelenga ! Finally I did it 🙂
=> Add MaxMindDB.cr to the list

README.md
=> Add LuckyFlow under testing

README.md
Add SushiChain Blockchain platform project under Blockchain
=> add SushiChain under Blockchain

README.md
It allows to deploy kemal (and another crystal apps)
=> Add capistrano-kemal

README.md
An easy to use configuration format parse. [config.cr](https://github.com/chris-huxtable/config.cr)
=> Adds config.cr

README.md
https://github.com/docelic/crystime
=> Add crystime - advanced time, calendar, schedule, and remind library for Crystal 

README.md
Reduces the opportunity for file corruption during write or append.
=> Adds `atomic_write.cr`

README.md
https://gitlab.com/crystallabs/crystime
=> Correct Crystime URL

README.md
Add regular expression tester to App & Services section
=> Add Crystular app

README.md
Adds a URL shortening utility used in production at https://express.mediaping.net
=> Add MPNGIN app

README.md
Hi i'm added [device_detected](https://github.com/creadone/device_detector) shard for detect client type by user-agent string. It is my first library on Crystal and I will be grateful if someone has time for a code review or tips for increasing performance.
This shard will be constantly improving, because I want to use it in production on my project http://to.click
=> Add device_detector shard

README.md
So Crystal Devs don't have to feel responsible for its content :wink: 
118 members ATM.
=> Add Russian-speaking Telegram Group to Community / Unofficial section

README.md, util/readme.cr
Adds [money](https://github.com/crystal-money/money) shard.
=> Add crystal-money/money shard

README.md
LinCAS-lang is a programming language designed for scientific computation.
=> Added LinCAS-lang project

README.md
[discordcr](https://github.com/meew0/discordcr) is a minimalist Discord API library (by the author of discordrb, meew0).
=> Add discordcr

README.md
Adds [base62.cr](https://github.com/Sija/base62.cr) shard.
=> Add base62.cr

README.md
=> Add a Resource

README.md
A Gopher toolkit. Serves basic requests at the moment, but I'm making it extensible so it can do more interesting things.
=> Add gopher.cr

README.md
Signed-off-by: Laurent Vallar <val@zbla.net>
=> add crun, shebang wrapper for Crystal

README.md
I now notice that there is an existing shard. Mine differs in that it uses sys-calls which would insure platform independence.
=> Adds syslog.cr

README.md
Yo I created a library a while ago that let's you do Design by Contract instead of Test Driven Development. I feel it is pretty solid as now and have all the features it needs. So I've bumped it to 1.0 version.
=> Add Crystal-Clear

README.md
Adds [retriable.cr](https://github.com/Sija/retriable.cr) shard.
=> Add retriable.cr

README.md
> [Callbacks](https://github.com/vladfaust/callbacks.cr) is an expressive callbacks module.
=> Add callbacks.cr

README.md
A new Crystal book is out and I just added it to the list. Also fixed the lowercase `f`in the resource entry some lines above :)
Chéers!
=> Add PragProg book to resources

README.md
I included this under __Tools__ section, is there a better place?
=> Add ast_helper

README.md
This is the beginning of a Socks implementation I wanted to add to the Network Protocol section.
=> Add Socks to Network Protocol Section

README.md
Added [Praetorian](https://github.com/ilanusse/praetorian). I know it doesn't comply with the 30-day rule yet but I wanted the PR open to remind me of this.
We can check any other requirements in the meantime.
=> Added Praetorian

README.md
Hi everyone. I hope it's cool to plug my child of labor `crytic` here, a mutation testing framework. Would love to get more people into mutation testing ✌️
Let me know what you think, I believe it checks all the boxes for listing it here?
=> Add crytic - a crystal lang mutation testing framework

README.md
The repository will be updated with more algorithms and data structures as time moves on.
=> included graphlb

README.md
Let me know if you think it would make more sense under a different category. Potentially it could go near Bson, Messagepack etc.
=> Added bitfield library to list under MISC.

README.md
=> maxminddb.cr divided into two shards

README.md
=> rethinkdb repo was updated v2

README.md
[Onyx::SQL](https://github.com/onyxframework/sql) (previously *Core*) is an SQL ORM with beautiful DSL and (almost all) type-safe Query builder.
=> Replace Core with Onyx::SQL

README.md
Hi,
I'm starting to get my repositories out of github, so I will update them on my own domain.
=> Migrate some repositories

README.md
implements an ASN.1 parser which can be used to implement SNMP and LDAP protocols
=> add bindata

README.md
It's been requested that I submit a PR for this, so here it is :)
=> Add watzon/cadmium

README.md
Monads is currently the most advanced shard for monad manipulation in Crystal.
It implement Maybe, Either, List and Task monads.
=> Add monads shard

README.md
Added:
https://github.com/spoved/vcr.cr
https://github.com/spoved/kube-client.cr
https://github.com/spoved/crafana.cr
=> Add spoved releases

README.md
Adds [Terminimal](https://github.com/aca-labs/terminimal) - a lightweight toolkit for displaying output from CLI apps.
=> Add terminimal

README.md
Added arachnid. A powerful web scraping framework.
It doesn't have specs yet because of how difficult specs are to write for a project like this, and because I will be transitioning from a standard http client to a headless chrome based client as soon as I finish [watzon/marionette](https://github.com/watzon/marionette), so if you don't want to merge yet I understand.
=> Added arachnid

README.md
Pure Crystal implementation of Tape archives (tar) readers and writers, supports most variations of the formats including those produced by GNU and BSD tar tools.
=> Added readers and writers of Tar archive format

README.md
Adds zstd-cr, binding to Zstandard compression library
=> Adds zstd-cr

README.md
Add Crystal Programming, unofficial Discord server dedicated to the Crystal Programming Language.
=> Add Crystal Programming

README.md
This group was created by me. Here is a small group of Chinese interested in Crystal!
=> Add @crystal_cn Telegram group link

README.md
Adds crystal-consul, api client for consul http api
=> added crystal-consul

README.md
Adds [debug.cr](https://github.com/Sija/debug.cr) shard to the `Tools` section - btw, what do you think about creating new section titled `Debugging`?
=> Add debug.cr shard

README.md
BlackHabanero's [project](https://github.com/BlackHabanero/zstd-cr) has been archived.
=> Zstd project change.

README.md
Signed-off-by: Derek Collison <derek@nats.io>
=> Added NATS client

README.md
Telnet protocol support for crystal lang
=> Add Telnet.cr

README.md
add [Tablo](https://github.com/hutou/tablo) shard : a flexible terminal table generator
=> Add Tablo shard

README.md
Crecto is back!
https://github.com/Crecto/crecto/issues/233#issuecomment-531911736
https://github.com/Crecto/crecto/commit/9c86cd89dafe493ee8e015169f9dff66b4bb7ba8
=> Add crecto back

README.md
The new entries have recent activity look functional.  Existing entries weren't validated.
=> Add compression section with new links.

README.md
I've been working on a little CLI builder for a while, finally got around to making it conform with your contributing guidelines. If there are any issues, please let me know.
Thanks for maintaining this useful list!
=> Added Phreak

README.md
* Adds https://github.com/blacksmoke16/oq
* Adds https://github.com/blacksmoke16/assert
* Adds https://github.com/blacksmoke16/crylog
* Moves `CrSerializer` to a different section
* Moves `Crystal-DI` to the DI section
=> Some additions

.gitignore, README.md, shard.yml, util/cli.cr
* Adds a CLI target to help with erroneous shard removal
* Generates a `shard_list.yml` file based on the lines in `README.md`.
* Resolves the VC and CI provider of each shard as well as last build time
* Generates a report of erroneous shards
* That don't have CI, that have CI but were never built, or if last build was more than a month ago
* Deletes shards that belong to one of those categories
* Implements the first phase of erroneous shard removal by removing shards that do not have CI setup
* PR is set as a draft to give some time for shard owners to get it setup.  Then will regenerate the report and update the PR.  Otherwise they will have to make a PR later once its setup.
Partially _resolves_ #412.
**DISCLAIMER:** I don't have a way to resolve shards using GitHub Actions, so if …
=> CLI helper script and phase 1 of erroneous shard removal

README.md
https://github.com/crystal-data/bottle
=> Added bottle

README.md
https://discord.gg/YS7YvQy
Previous link accidentally died as a result of server changes. This is the new one.
=> Update Crystal Programming invite link

README.md
[https://github.com/jetrockets/shrine.cr](https://github.com/jetrockets/shrine.cr)
=> Added shrine.cr

README.md
https://github.com/NeuraLegion/har
=> Add HAR shard

README.md
The shard was already approved a while ago, but the name has changed.
=> Bottle has been renamed to num.cr

README.md
https://github.com/firejox/CrSignals
=> Add CrSignals

README.md, util/cli.cr
* Continues #453 by removing shards that have CI, but has never been ran.
* Adds some additional shards to the exempt list, if there are anymore that should be there let me know
* Not sure if they're all still maintained tho :man_shrugging:
* Fixes owner of cadmium \cc @watzon 
Let me know in the comments if you setup period CI builds and I can update the list/add the shard back.
https://github.com/Angarsk8/realtime-todo-app - @Angarsk8
https://github.com/ChangJoo-Park/kemal-vue-chat - @ChangJoo-Park
https://github.com/DougEverly/slack.cr - @DougEverly
https://github.com/Fusion/libui.cr - @Fusion
https://github.com/Papierkorb/qt5.cr - @Papierkorb
https://github.com/Qwerp-Derp/hedron - @Qwerp-Derp
~https://github.com/RX14/predict.cr - @RX14~
https://github.com/TechMagister/bindgencr - …
=> Round two of erroneous shard removal

README.md
https://github.com/cocol-project/cocol
https://github.com/q9f/secp256k1.cr
=> Adding Cocol and secp256k1.cr

README.md
https://github.com/hugopl/queryit
CI is configured for monthly builds.
=> Add queryit to Database Tools section.

README.md
https://gitlab.com/jgillich/crystal-dns
=> add crystal-dns

README.md
=> Add fzy to algorithms section.

README.md
=> Add Portuguese-speaking Telegram Group to Community/Unofficial section

README.md
https://github.com/Nicolab/crystal-validator
=> Add validator

README.md
https://github.com/ujjwalguptaofficial/shivneri
=> add shivneri framework

README.md
https://github.com/cloudamqp/amqp-client.cr
=> amqp-client.cr

README.md
I wasn't immediately sure if adding multiple projects was acceptable, but then I saw https://github.com/veelenga/awesome-crystal/pull/451 and thought, maybe so... I'm happy to break these up and/or leave anything out that's not of note or mature enough.
* https://github.com/toddsundsted/mxnet.cr
* https://github.com/toddsundsted/ishi
* https://github.com/toddsundsted/iterm2
* https://github.com/toddsundsted/public_suffix
* https://github.com/toddsundsted/host_meta
* https://github.com/toddsundsted/web_finger
* [-] - Shard is at least 30 days old*.
All CI is on Travis (https://travis-ci.org/toddsundsted).
* Ishi and Iterm2 are currently only 18 days old, but both are an important part of the visualization work I do with MXNet, so they will both see their 30-day birthday. I'm happy to wait …
=> Adds Projects

README.md
https://github.com/tilishop/mollie.cr/
<strike>I know this shard is only 27 days old but it is not a flimsy project. It's</strike> This is a complete port of it's [Ruby sister](https://github.com/mollie/mollie-api-ruby), and a key requirement for two large crystal (Lucky) projects I am working on. So it won't disappear into oblivion any time soon.
=> Added Mollie API wrapper.

README.md
Hi!
I'm submitting my shard HardWire !
I've implemented CI + nightly builds on the mainline master branch using GitHub Actions.  
Let me know if you spot anything else I've missed 🙄
https://github.com/jerometwell/hardwire
=> Add jerometwell/hardwire to Dependency Injection

README.md
https://github.com/PlaceOS/google
https://github.com/PlaceOS/office365
=> Add Google and Office365 / MS Graph API wrappers

README.md
https://github.com/Sija/gphoto2-web.cr
=> Add gphoto2-web.cr

README.md
https://github.com/RomainFranceschini/quartz
=> Add quartz 

README.md
https://github.com/spoved/entitas.cr
=> Addition of spoved/entitas.cr

README.md, util/cli.cr
Didn't get to it in time before removal PR was merged.  Readds them as per https://github.com/veelenga/awesome-crystal/pull/489#issuecomment-624968485.
=> Readd sendgrid.cr

README.md
https://github.com/Sija/blurhash.cr
=> Add blurhash.cr

README.md
We have one episode released 2 in the pipeline and 1 scheduled to record.
=> Chicago Crystal podcast

README.md
https://github.com/runcobo/runcobo
=> Add runcobo

README.md
https://github.com/confact/stripe.cr
=> Added stripe.cr

README.md
https://github.com/microgit-com/linguist.cr
=> Add linguist.cr

README.md
https://github.com/spider-gazelle/crystal-mqtt
=> Add MQTT client

README.md
https://github.com/spider-gazelle/crystal-ldap
=> Add LDAP client

README.md
https://github.com/Sija/climate.cr
=> Add climate.cr

README.md
https://github.com/anicholson/crystal-version-tools
=> Add version_tools

README.md
we are posting to both these platforms now and they do not have a shared link.
https://www.youtube.com/channel/UCI1RvHPG6S9mw4eRoJfH2kA
=> Breaking Chicago Crystal into 2 links

README.md
https://github.com/elbywan/cryomongo
=> Add cryomongo

.gitignore, README.md
https://github.com/ilmanzo/crystal-koans
=> add crystal-koans

README.md
https://github.com/spider-gazelle/digest-auth
=> Add HTTP digest authentication

README.md
https://github.com/place-labs/secrets-env
=> add secrets-env

README.md
https://github.com/grkek/iu
I don't think an UI framework needs a CI to keep it in check?
=> Add IU - UI framework based on the Fusion/libui.cr library

README.md
=> Remove dead CLI Utils link

README.md
https://github.com/oprypin/crystal-imgui
https://github.com/oprypin/crystal-imgui-sfml
=> Add crystal-imgui and crystal-imgui-sfml

README.md
https://github.com/andrewc910/motion.cr
=> Add motion.cr to README

README.md
https://github.com/aristotelesbr2014/docx_cr_converter
=> Added DOCX library reference

README.md
https://github.com/grottopress/shield
=> Add `GrottoPress/shield`

README.md
https://github.com/NeuraLegion/wafalyzer
=> Add Wafalyzer

README.md
A tiny lib that provides efficient compression and decompression of a series of coordinates.
https://github.com/buonomo/polylines.cr
=> Add polylines.cr

README.md
Please merge this pull request to update the description of the Grip framework shard.
=> Update the description of the Grip shard.

README.md
Hey @veelenga 
just fixing a link.
Cheers
=> Fixing wikicr link

README.md
https://github.com/grottopress/envy
=> Add `GrottoPress/envy`

README.md
https://github.com/spider-gazelle/mdns
=> add mDNS - Multicast DNS

README.md
https://github.com/NeuraLegion/sslscan.cr
=> Add sslscan.cr

README.md, shard.lock, util/cli.cr
* Replaces `assert` with https://github.com/athena-framework/validator
* Updates owner/shard/repo names for some shards
* Removes inactive shards
=> Some updates

README.md
https://github.com/redcodefinal/celestine
* [ x] - Shard is at least 30 days old.
* [x ] - Shard has CI implemented.
* [ x] - Shard has daily/weekly periodic builds (ideally with Crystal latest and nightly).
=> Added Celestine

README.md
https://github.com/spider-gazelle/qr-code
Main difference between this and others out there is that this doesn't require any external dependencies
=> add qr-code

README.md, util/cli.cr
* Adds some additional Athena components
* Removes inactive shards
* Fix shard that was moved into an org
* https://github.com/athena-framework/negotiation
* https://github.com/athena-framework/spec
NOTE: README badge says CI is failing but it's just nightly tests due to https://github.com/crystal-ameba/ameba/pull/184.
=> Add & Remove some shards

README.md
https://github.com/Anyolite/anyolite
=> Added Anyolite

README.md
https://github.com/spider-gazelle/s2_cells
=> add s2 cells

README.md
https://github.com/spider-gazelle/stomp
=> add STOMP protocol

shard.lock, shard.yml, util/cli.cr
* Support transferred repos
* Use more OOP patterns to make it easier to maintain
* Fix Crystal deprecations
* Use Log module instead of pp and puts
* Support `1.0.0`
=> Refactor CLI

README.md
I am adding two of my shards with this PR.
https://github.com/wyhaines/splay_tree_map.cr
https://github.com/wyhaines/serf-handler.cr
=> Add SplayTreeMap and Serf-Handler

README.md
https://github.com/Sija/backtracer.cr
=> Add backtracer.cr

.github/workflows/ci.yml, .travis.yml
Unblocks #556 and #558.
Will need to replace the current required with the new one.
=> Replace TravisCI with a Github Action

README.md
(https://github.com/kostya/simple_rpc
* [+] - Shard is at least 30 days old.
* [+] - Shard has CI implemented.
=> add simple_rpc

README.md
https://github.com/mmacia/tmdb.cr
=> add TMDb api wrapper

README.md
https://github.com/spider-gazelle/crystal-bacnet
=> add crystal-bacnet

README.md
https://github.com/syeopite/lens
=> Add Lens - a multiformat internationalization shard

README.md
https://github.com/wout/rosetta
https://wout.github.io/rosetta/latest
=> Add Rosetta under internationalization

README.md
https://github.com/automatico/mac-address
=> Add MAC addresses Library

README.md, shard.lock, util/cli.cr
* Remove explicitly abandoned shards
* Fix some transferred shards
* Update cli to account for GH Action workflows going inactive
* Fix some typos
***
https://github.com/athena-framework/console
=> Add Athena Console & small readme refresh

README.md
https://github.com/firejox/fftw.cr
=> Add FFTW.cr

README.md
https://github.com/naqvis/wasmer-crystal
No- shard is brand new, although Wasmer is well-established. Please consider merging in January.
=> Add wasmer-crystal

README.md
I have been using this package heavily in some other libraries. It provides facilities to enable conditional compilation based on whether or not a constant exists, version numbers match requirements, or environment variables are defined (or not). Recent documentation should cover the use cases. There is spec coverage, and specs are set up to run nightly.
I am unsure if there is a better category for this than misc, but nothing jumped out at me when I was scanning the list.
=> Add defined.cr to the Misc category.

README.md
https://github.com/didactic-drunk/concurrent.cr
=> Add concurrent.cr

README.md
https://github.com/didactic-drunk/fiber_metrics.cr
=> Add fiber_metrics.cr

README.md
https://github.com/spider-gazelle/secure-remote-password
=> add Secure Remote Password

README.md
A newer alternative MQTT client
https://github.com/84codes/mqtt-client.cr/
=> mqtt-client.cr

README.md
the Ed25519 elliptic curve public-key signature system described in [RFC 8032]
https://github.com/spider-gazelle/ed25519
=> add Ed25519 public-key signature system

README.md
https://github.com/hugopl/gtk4.cr
=> Add GTK4.cr to GUI section.

README.md
Direct bindings to SDL2, including a generator script.
https://github.com/Hadeweka/SDL-Crystal-Bindings
=> Add SDL-Crystal-Bindings

README.md
https://github.com/spider-gazelle/ffmpeg
=> add FFmpeg

README.md
Hi! This is a CLI tool to create Kubernetes clusters in Hetzner Cloud. It's not a shard.
https://github.com/vitobotta/hetzner-k3s
=> Add hetzner-k3s

README.md
This is a link to a website dedicated to Crystal GTK4 developent. Though not a shard, a myst have on this list
=> Multiple authoritive GUI urls

README.md
=> Add procodile, hashr, port_ruby_to_crystal

README.md
https://github.com/yorci/surrealdb.cr
=> add surrealdb.cr

README.md
https://github.com/devnote-dev/cling
=> feat: add cling

README.md
https://github.com/asedunov/intellij-crystal-lang
=> Add IntelliJ plugin to the supported editors list

README.md
https://github.com/place-labs/git-repository
=> add git-repository

README.md
https://github.com/novika-lang/novika
=> Add novika

README.md
=> Update Resource Section

README.md
https://github.com/mjblack/win32cr
=> Add win32cr

README.md
https://github.com/sol-vin/raylib-cr
=> Add raylib-cr

README.md
I just archived this project since I don't work on it in ages and also don't plan to work on it anymore.
=> Remove queryit from list.

README.md
Soegen is outdated and will be archived.
=> Remove soegen

README.md
=> Removed dead links. Resolved #619

README.md
[verhoeff](https://github.com/spider-gazelle/verhoeff)
=> add Verhoeff

README.md
[named_information](https://github.com/spider-gazelle/named_information)
=> add named_information

README.md
https://github.com/spider-gazelle/SPAKE2_plus
=> add SPAKE2+

README.md
- https://shards.info/github/BT-OpenSource/crafka/
=> Add crafka

README.md
=> Adds cr-cmark-gfm to readme

README.md
https://github.com/yanecc/vfox-crystal
=> Add vfox-crystal version management plugin

README.md
https://github.com/spider-gazelle/knx
=> add KNX protocol

README.md
https://github.com/spider-gazelle/dns
=> replace DNS

README.md
Source code : https://github.com/qequ/jmespath.cr
Shard link : https://shards.info/github/qequ/jmespath.cr/readme
=> Add jmespath.cr

README.md
* https://github.com/owasp-noir/noir
* https://github.com/hahwul/xssmaze
* https://github.com/hahwul/cyclonedx-cr
* This doesn't comply with the 30-day policy of the checklist. 
* If needed, I can add a commit to remove it!
----
I added a security section since it was missing and included a few tools. Please let me know your thoughts!
=> Add security section and tools
