veelenga/awesome-crystal

README.md

After merging this pull request the `awesome-crystal` list will include a reference to the [crystal-docs](https://crystal-docs.org) website.
It may be worth noting that the `docrystal` project has been broken for awhile now (at least a few months) as it compiles the documentation for shards, which requires that both the compiler and the shards are compatible, which seems to never be the case.

Add crystal-docs website to the list.

---

README.md

Hi! I added my `ms` library.
It helps convert time formats (like `5 sec` / `1 year` / `day`) to milliseconds, and milliseconds to human readable format.
```crystal
require "ms"
MS.ms("50 min")
MS.ms(1000)
```

Add `ms` library

---

README.md

Hi,
I added another image library ([stumpy_gif](http://github.com/l3kn/stumpy_gif)) and updated the description for [stumpy_png](http://github.com/l3kn/stumpy_png) because it is now possible to write `.png` files.

Add stumpy_gif and update the description for stumpy_png

---

README.md

Topaz is a simple and useful db wrapper for crystal-mysql.
Topaz is still developing but released first version v0.0.1.
For detail, https://github.com/tbrand/topaz

Added topaz 

---

README.md

[magickwand-crystal](https://github.com/blocknotes/magickwand-crystal)
Added to **Low level bindings** section

Add magickwand-crystal

---

README.md

[slack.cr](https://github.com/DougEverly/slack.cr)
Added to Third-party APIs section
- [√] Tests pass (`crystal spec`)
- [√] Description of the entry is clear and concise. There is no excessive information like

Added slack.cr RTM API client library to Third-party APIs.

---

README.md

[curl-crystal](https://github.com/blocknotes/curl-crystal)
Added to **Low level bindings** section

Added curl-crystal

---

README.md

[awscr-signer](https://github.com/taylorfinnell/awscr-signer)

Add awscr-signer

---

README.md

[kemal-rest-api](https://github.com/blocknotes/kemal-rest-api)
Added to **Api Builders** section

Add kemal-rest-api

---

README.md

[mime-types.cr](https://github.com/jwaldrip/mime-types.cr) - A port of the Ruby MIME-types library
Added to **Framework Components** section

Add mime-types.cr

---

README.md

[manual-generator](https://github.com/blocknotes/manual-generator)
Added to **Misc** section

Add manual-generator

---

README.md

This PR adds [ipaddress.cr](https://github.com/Sija/ipaddress.cr) shard to the list.
Added to **NETWORKING** section

Add ipaddress.cr shard

---

README.md

[bugsnag.cr](https://github.com/gewo/bugsnag.cr)

Add bugsnag.cr

---

README.md

[admiral](https://github.com/jwaldrip/admiral.cr) - A robust DSL for writing command line interfaces.
Added to **CLI Utils** section

Add Admiral

---

README.md

[charly](https://github.com/charly-lang)
Added to **Implementations/Compilers** section

Updated links to charly-lang

---

README.md
spec/readme_spec.cr

[crometheus](https://gitlab.com/ezrast/crometheus)
Added to **Logging and monitoring** section
I host on GitLab so I also added analogs for the GitHub-specific test cases.

Add Crometheus

---

README.md

[crystal-github](https://github.com/felipeelias/crystal-github)

Add crystal-github API wrapper

---

README.md

Добавлена ссылка на новую библиотеку [ocean_kit](http://github.com/osfx/ocean_kit). 
Изменил ссылку [haikunator](http://github.com/osfx/haikunator) он перехал.

Add link to ocean_kit & change link to kaikunator

---

README.md

[lattice-core](https://github.com/jasonl99/lattice-core)
[lattice-core-card-game](https://github.com/jasonl99/card_game)
Added to **Web Frameworks** and **Examples and funny stuff** sections

Add lattice-core (with demo app)

---

README.md

[crystalg.cr](https://github.com/TobiasGSmollett/crystalg)
Added to **Algorithms and Data structures** section

Add crystalg.cr

---

README.md

[eventql-crystal](https://github.com/measurechina/eventql-crystal)
Added to **Database Drivers** section
- [v] Tests pass (`crystal spec`)
- [v] Description of the entry is clear and concise. There is no excessive information like

Add eventql-crystal

---

README.md

[route.cr](https://github.com/tbrand/route.cr)
Added to **route.cr** section

Added route.cr

---

README.md

[crystal-darksky](https://github.com/sb89/crystal-darksky)

Added crystal-darksky

---

README.md

Hi,
Thanks for this awesome list!
`sctp-crystal` is currently broken and will most likely be discontinued.

remove sctp-crystal

---

README.md

Hi @veelenga  :smile: !
I added another VSCode' extension: [vscode-crystal-lang](https://github.com/faustinoaq/vscode-crystal-lanºg).
This extension has a formatter, linter and syntax highlighting for `cr` and `ecr` files.

Add new VSCode extension

---

README.md

[Previous shard](https://github.com/whity/crystal-i18n) is outdated, as well as two others.

Add i18n.cr

---

README.md

CrystalIrc is now depreciated, because we rebuilt it from scratch (breaking changes) and named the new project Crirc.

Remove CrystalIrc and add Crirc

---

README.md

[micrate.cr](https://github.com/juanedi/micrate) is abandoned - it has forever pending pull requests with needed features and never updated issues.
I've developed a simpler solution ([migrate](https://github.com/vladfaust/migrate.cr)), which resolves following issues:
- https://github.com/juanedi/micrate/issues/11
- https://github.com/juanedi/micrate/issues/13
- https://github.com/juanedi/micrate/issues/19
- https://github.com/juanedi/micrate/issues/20
- https://github.com/juanedi/micrate/issues/21
It may be possible to migrate from micrate to migrate :smile:: just add a table called `"version"` with a single `"version"` column with your latest migration version value. Also need to replace `-- +micrate Up/Down` with `-- !migrate up/down`, which is more universal.
Cheers.

Add migrate

---

README.md

I'm not sure if this is the right places in the list, but I've added [my mosquito project](https://github.com/robacarp/mosquito/) to the Queue section. It also includes jobs which are scheduled (eg every X minutes), so I considered putting it in the `Scheduling` section, but it is intended firstly as a replacement for sidekiq so I put it alongside.

Adds mosquito

---

README.md

Hi @veelenga 
This PR adds 2 new shads:
1. Scry - LSP for crystal https://github.com/crystal-lang-tools/scry
2. ~~Mint - A refreshing programming language for the font-end web. https://www.mint-lang.com~~

Add scry and mint

---

README.md

I wrote migro as I wanted a better SQL migration tool than e.g. Liquibase or Flyway. While there are existing database migration tools written in Crystal already, they're limited to migrations written in SQL.
With migro, you can specify migrations in YAML or SQL. In the future, I hope to support automatic rollback for migrations written in YAML (ala ActiveRecord Migrations).

Added migro

---

README.md

The link pointing to granite orm is deprecated, fixed to pointing the new one.

fix granite link

---

README.md

I've changed `Virtualization` to a more generic `System` because `baked_file_system` implements VFS , that isn't really virtualization (the system one). The one left that do virtualization is `rcpu`, which is included in system.

Add hardware to System

---

README.md

Hedron is a small GUI library I've been working on lately. So far, what's in the library is this:
- Fully object-oriented, based off of [libui](https://github.com/andlabs/libui)
- Features a markup language, HDML
- Allows for the creation of new "widgets" (base class for all UI elements), and allows for integration between custom widgets and HDML

Add hedron to GUI libraries

---

README.md

Yep, the [shard](https://github.com/vladfaust/tarantool-crystal) is just forged, but I want impatiently the community to know that the a super-fast in-memory DB has finally met with a super-fast compiled language! :zap: 
It currently has no releases yet, grab from master. In a couple of days I'll release `v0.1.0` when issues left are closed.
Cheers!

Add tarantool-crystal

---

README.md

[front_matter.cr](https://github.com/chris-huxtable/front_matter.cr)

Adds front_matter.cr

---

README.md

A shard that provides Crystal performance visibility by collecting distributed traces and runtime metrics.
It's also one of the very few (only?) valid [OpenTracing](http://opentracing.io/) tracers for Crystal.

Add instana shard to Logging & Monitoring

---

README.md

Mass Spec is a Web API testing library that supports most of the Crystal web frameworks (tested with Kemal and Amber currently).
It also prevents HTTP::Server from starting a TCPServer and use IO::Memory instead of TCPSocket for fast testing.
Added to **Testing** section:
* [mass-spec](https://github.com/c910335/mass-spec) - Web API testing library

Add mass spec

---

README.md

Adds [gcf.cr](https://github.com/sam0x17/gcf.cr), which allows crystal code to run "serverless" in a Google Cloud Function. This consists of both a crystal API for integrating with Google Cloud Functions, and the `gcf` command line tool for managing and deploying to Google Cloud Functions (both are built from the same shard).
I added it to the third party API section because there is no serverless section, but please comment if you think a new category should be created or if it makes more sense in a different category and I will make the necessary changes.
edit: now in the newly created "Serverless Computation" category

add gcf.cr

---

README.md

Compared with [accord](https://github.com/neovintage/accord), [validations.cr](https://github.com/vladfaust/validations.cr) aim at inline attributes validation other than defining a separate `def validate` method.
Compared with [denetmen](https://github.com/izniburak/denetmen), [validations.cr](https://github.com/vladfaust/validations.cr) is an entity mixin other than separate objects patcher.
It's still a PR and can be declined if community decides it's not needed.

Add validations.cr

---

README.md

[Crystal World](https://github.com/vladfaust/crystalworld) is a [realworld.io](https://realworld.io) back-end API application implemented in Crystal.
The issue has been there for a long time: https://github.com/gothinkster/realworld/issues/223.

Add Crystal World

---

README.md

```crystal
require "compiled_license"
```
Compile and run
```
$ crystal build src/testapp.cr
$ testapp --licenses
```

Adds compiled license to list under MISC for now.

---

README.md

We have transferred and renamed `manastech/crystal-toml` to `crystal-community/toml.cr`.
Best regards,

Rename manastech/crystal-toml to crystal-community/toml.cr

---

.github/CONTRIBUTING.md

Closes https://github.com/veelenga/awesome-crystal/issues/347.
The community may want to add other CI services. I use Travis CI only.

Require periodical builds

---

README.md

Rawgit is shutting down, see [here](https://rawgit.com/). This PR fixes the URL.

Replacing rawgit url as it's shutting down

---

README.md

I created a template implementation so that Crystal can be used with openFaaS just like other first-class citizens (like go and ruby)

add crystal_faas_template

---

README.md

This PR adds a link to `WebdriverPump`, a Page Object pattern implementation, heavily inspired by Ruby's `WatirPump`.

Add testing/webdriver_pump (Page Object lib)

---

README.md

[Onyx::REST](https://github.com/onyxframework/rest) (previously *Prism*) is a REST API framework with type-safe params and separate layers -- business with `Action`s and rendering with `View`s. It is based on [Onyx::HTTP](https://github.com/onyxframework/http) (there will be Onyx::GraphQL which would also be based on Onyx::HTTP, that's why I'm emphasizing it).

Replace Prism with Onyx::REST

---

README.md

reasons for replacement
* project inactivity
* all IO blocks the crystal lang event loop
* incompatible with crystal 0.7+

replace ssh2.cr

---

README.md

[http-params-serialializable](https://github.com/vladfaust/http-params-serializable) shard adds the `HTTP::Params::Serializable` module similar to `JSON::Serializable` and its siblings, which allows to (de)serialize URL queries and URL-encoded forms like a boss :sunglasses: 
It is used in [Onyx::REST](https://github.com/onyxframework/rest) to implement type-safe params.

Add HTTP::Params::Serializable

---

README.md

[pangu.cr](https://github.com/isaced/pangu.cr) - Paranoid text spacing for good readability, to automatically insert whitespace between CJK (Chinese, Japanese, Korean) and half-width characters (alphabetical letters, numerical digits and symbols).

Add pangu.cr

---

README.md

This PR is for adding [can_use](https://github.com/rodrigopinto/can_use) shard to the list on the Feature Toggles section.

Adding `can_use` shard to the list.

---

README.md

Dead simple HTML form builder for Crystal with built-in support for many popular UI libraries such as Bootstrap. Works well with your favourite Crystal web framework such as Kemal, Amber, or Lucky.
I created this shard to address a need in the Crystal community for an HTML form builder. This appears to be the only shard dedicated solely to form building for the language so far.
https://github.com/westonganger/form_builder.cr
Note: I thought it was appropriate to create a new category for "HTML Builders" instead of burying this stuff in the "Misc" junkdrawer. Let me know your thoughts on this or if we should to rename it.

Add form_builder.cr

---

README.md

Add HTML Builders section to TOC

---

README.md

Crecto is no longer actively maintained :(
I want to keep this list current but I would hope crecto would find a supporter. 
here is the link from the maintainer https://github.com/Crecto/crecto/commit/4bf83cbfc1fdf6cf4efef05ac0fe6c72b826d90f

remove crectro

---

README.md

tallboy is a library for generating ASCII character tables with support for spanning cells over multiple columns. Which is a feature missing even in similar popular libraries in goland, js, python & ruby
https://github.com/epoch/tallboy

add tallboy to CLI Utils

---

README.md

Adds Development Tools -> [docker-crystal](https://github.com/aca-labs/docker-crystal): a docker wrapper for the Crystal CLI.

add docker-crystal

---

README.md

A list of popular github projects related to Crystal web framework (ranked by stars automatically),It will update automatically.
Inspired by [go-web-framework-stars](https://github.com/mingrammer/go-web-framework-stars).

Add 'crystal-web-framework-stars'

---

README.md

The datanoise/mongo.cr shard, which hasn't been updated for 11 months as of April 2019,
has been forked into Amber Community organisation and commits applied from a number of other forks to bring it up to date.  In particular update to support crystal 0.27.1.

use the mongo.cr shard from ambercommunity

---

README.md

Hi @veelenga,
this PR adds [spectator](https://gitlab.com/arctic-fox/spectator).

Add spectator (spec framework)

---

README.md

Add [ynab.cr](https://github.com/jaredsmithse/ynab.cr), a wrapper for the YNAB API.

Add ynab.cr to third-party APIs list

---

README.md

Apologies for the name change so quickly after the last PR.  My most recent work has changed all of the API  (there were only 4 calls to begin with) to be more in line with other libsodium implementations.  I felt it best to list mine as a different project on github to avoid confusion.
Project history was added at the bottom if you're curious.

cox changed to sodium.cr

---

README.md

I have been using this library for a while now and am surprised it was not on the list.

Add Syringe to list under dependency injection.

---

README.md

Implements the HTTP CONNECT method for tunnelling raw sockets.
Also provides a HTTP Client implementation that can be used for connecting to HTTP servers via a connect proxy

Add connect-proxy

---

README.md

Crystal port of Ruby [ProxyFetcher gem](https://github.com/nbulaj/proxy_fetcher) for fetching and validating proxy lists from different sources.

Add proxy-fetcher.cr to the list

---

.github/PULL_REQUEST_TEMPLATE.md

Adds a PR template to bring increased visibility to the requirements when adding a new shard; as well as making reviewing easier.

Add PR template to standardize adding new shards

---

README.md

https://github.com/grip-framework/grip (old link was https://github.com/grkek/grip , which is dead :skull: )

Fix link to grip, now under organization instead of user

---

README.md

I have no idea if the project is mature enough to warrant being on here. I use this library for a handful of my own utilities and it's been great. I don't have tests written for it. I just think it'd be good to get some other eyes on it.
I also don't know if it should be in CLI Builders or CLI Utilities. The list of builders is _essentially_ just option parsers, but utilities are ... applications which run in the console.

Add Keimeno TUI engine

---

README.md

[Logger](https://crystal-lang.org/api/Logger.html) is now deprecated in favor of [Log](https://crystal-lang.org/api/Log.html)

Replace Logger with Log

---

README.md

https://github.com/vim-crystal/vim-crystal
I moved [vim-crystal](https://github.com/vim-crystal/vim-crystal) to new organization. This PR updates the repository URL.

Update vim-crystal repository URL

---

README.md

retriable.cr is not fit for purpose in its current state https://github.com/Sija/retriable.cr/issues/8
we built a simplified version after we discovered the issue above. It was causing havoc with our services
https://github.com/spider-gazelle/simple_retry

add simple_retry

---

util/cli.cr

https://github.blog/changelog/2020-03-24-github-actions-api-is-now-generally-available/
API support for GH Actions was made available a few months ago.  This PR allows resolving shards using GH Actions via the GitHub API, versus a static list.
There is a ratelimit on the API, so authentication is required.

Resolve CI::Actions via API

---

README.md

https://github.com/graphql-crystal/graphql
This might be a bit confusing with both `graphql` and `graphql-crystal`, but ziprandom hasn't been particularly active for about two years, and I think my type-safe implementation is superior, that's why I went ahead and used the name anyway. There's a section in my readme that explains the differences between the two.

Add graphql

---

README.md

A serialization shard, which differs from the stdlib's by not requiring to `include` any module.
https://github.com/j8r/crystalizer

Add Crystalizer

---

README.md

I replaced the entire *Editor support* section on https://github.com/crystal-lang/crystal/wiki with a link to this section here, so in the future there's only one place to keep updated.

Update Editor Plugins

---

README.md

a HTTP Link Header Parser
https://github.com/spider-gazelle/link-header

add link-header

---

.github/workflows/ci.yml
.travis.yml
README.md
util/cli.cr

Looks like CI works @veelenga.  Will want to make the new one required and the other not required now tho.

README fixes/removals

---

README.md

https://github.com/spider-gazelle/crunits
Currently only supports crystal 1.1.0 and above due to limitations with BigDecimal on 1.0.0
but should be good to go in the next 30 days

add crunits

---

README.md

https://github.com/wyhaines/csuuid.cr
This shard is one of my older ones, and has been in use in myriad other places for a couple years. I just did a little doc cleanup, and bumped it to 1.0.0.

Add the CSUUID shards to the algorithms list.

---

README.md

convert JSON serializable classes into a [JSON Schema](https://json-schema.org/) representation
https://github.com/spider-gazelle/json-schema

add json-schema

---

README.md

An unofficial SDK supporting popular AWS APIs.
https://github.com/rjnienaber/amazonite

Add Amazonite library

---

README.md

https://crystalshards.xyz isn't working anymore.
https://crystalshards.herokuapp.com isn't working too
https://crystalshards.org works.

fix Crystal Shards link

---

README.md

Makes more sense as it's used to build HTML, without templating features.
ref: https://github.com/veelenga/awesome-crystal/pull/613#issuecomment-1511513028

Move `water` shard to `HTML Builders` section

---

README.md

https://github.com/sbsoftware/to_html.cr
Note: The repo itself is quite young because the code has been extracted from another project. I am using this shard in production builds regularly.

Add `to_html` shard to HTML Builder section

---

README.md

The last Crystal Weekly Newsletter was on 2022.
There is a new section on the official page to subscribe https://crystal-lang.org/#newsletter.

Replace Weekly newsletter with official newsletter

---

README.md

Several of these have been inactive for 3+ years. I think having links to defunct community projects makes crystal a bit bruised.

Removes defunct community links

---

README.md

add [gpio.cr](https://github.com/spider-gazelle/gpio.cr) linux general purpose IO bindings
useful for controlling and getting feedback on raspberry pi IO headers
https://github.com/spider-gazelle/gpio.cr
no CI as requires hardware but there are tests implemented and working in production projects such as my [chicken door](https://vontaka.ch/chicken_door/)

add libgpio bindings

---

README.md

https://github.com/crystal-china/sentry/releases
there is some discuss in the [form](https://forum.crystal-lang.org/t/sentry-is-reborn/7474/6)
* [ * ] - Shard is at least 30 days old.
* [ * ] - Shard has CI implemented.
* [ * ] - Shard has daily/weekly periodic builds (ideally with Crystal latest and nightly).

Add sentry shards and rename procodile_cr to procodile

---

README.md

Recommend Lexbor over MyHTML, because the [Github README](https://github.com/kostya/myhtml?tab=readme-ov-file#warning-original-libraries-myhtml-and-modest-not-maintained-since-july-2020-i-recommend-switch-to-successor-parser-lexbor) of MyHTML says:
> WARNING: original libraries (myhtml and Modest) not maintained since july 2020, i recommend switch to successor parser: Lexbor.
https://github.com/kostya/lexbor

Recommend Lexbor over MyHTML
